Repository Huluvu424242/honey-slideshow, pull requests merged in 2020-07, with the labels that each got.

#42 #43 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#45 close #44/singlebundle
  .github/workflows/github-upload.yml
  docs/index.html
  package-lock.json
  package.json
  readme.md
  src/components/honey-slideshow/custom-elements.json
  src/components/honey-slideshow/honey-slideshow.tsx
  src/components/honey-slideshow/test/edge-cases/honey-slideshow.e2e.ts
  src/components/honey-slideshow/test/smoke/a11y.e2e.ts
  src/components/honey-slideshow/test/smoke/basics.e2e.ts
  src/components/honey-slideshow/test/smoke/honey-slideshow.spec.ts
  src/index.html
  stencil.config.ts
Labels: enhancement

#46 #44/singlebundle
  docs/demo.css
  docs/index.html
  readme.md
  src/components/honey-slideshow/custom-elements.json
  src/components/honey-slideshow/design.css
  src/components/honey-slideshow/honey-slideshow.tsx
  src/global/global.css
  src/index.html
Labels: enhancement

#50 close #49 secure issue
  package-lock.json
  readme.md
Labels: bug
